[workspace]
members = [
    "easy/solve-me-first",
    "easy/compare-the-triplets", 
    "easy/a-very-big-sum", 
    "easy/diagonal-difference", 
    "easy/plus-minus", 
    "easy/staircase", 
    "easy/min-max-sum",
]

resolver = "2"
